site_name: DeckThemes Docs
theme:
  name: material
  features:
    - toc.integrate
    - navigation.instant
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

nav:
  - Home: "index.md"
  - Install: "Install.md"
  - Submit: "Submission.md"
  - AudioLoader: "AudioLoader/index.md"
  - CssLoader: 
    - Home: "CSSLoader/index.md"
    - CEF Debugger: "CSSLoader/Cef_Debugger.md"
    - Features: "CSSLoader/Features.md"
    - Visualizer: "CSSLoader/Visualizer.md"
    - Presets: "CSSLoader/Presets.md"
  
markdown_extensions:
  - toc:
      permalink: true