site_name: DeckThemes Docs
theme:
  name: material
  features:
    - toc.integrate
    - navigation.instant
    - navigation.footer
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

nav:
  - Home: "/"
  - Install: "/Install"
  - Submit: "/Submission"
  - AudioLoader: "/AudioLoader/"
  - CssLoader: 
    - Home: "/CssLoader/"
    - CEF Debugger: "/CSSLoader/Cef_Debugger/"
    - Features: "/CSSLoader/Features/"
    - Visualizer: "/CSSLoader/Visualizer/"
    - Presets: "/CssLoader/Presets"
  
markdown_extensions:
  - toc:
      permalink: true

extra:
  version:
    provider: mike