site_name: DeckThemes Docs
repo_url: https://github.com/DeckThemes/DeckThemes-Docs
repo_name: DeckThemes-Docs
theme:
  name: material
  favicon: favicon.ico
  features:
    - toc.integrate
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tracking

  palette: 
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/paint-roller

nav:
  - Home:
    - Home: "index.md"
    - Submit: "Submission.md"
  - CSS Loader: 
    - Home: "CSSLoader/index.md"
    - Install: "CSSLoader/Install.md"
    - Theming Step By Step: "CSSLoader/theming_step_by_step.md"
    - CEF Debugger: "CSSLoader/Cef_Debugger.md"
    - Features: "CSSLoader/Features.md"
    - Visualizer: "CSSLoader/Visualizer.md"
    - Presets: "CSSLoader/Presets.md"
  - AudioLoader: 
    - Home: "AudioLoader/index.md"
    - Install: "AudioLoader/Install.md"
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DeckThemes
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@suchmeme.nl
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HsU72Kfnpf
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/deckthemes